# -*- coding: utf-8 -*-
"""Traditional_Chatbot_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqEW_SIKOD-8jLGJ0408WwGsjnJnc_3i
"""

print("Hello World")

# ===========================================
# Student Help Chatbot
# Traditional Rule-Based Chatbot
# Created using Python in Google Colab
# ===========================================

# Display welcome message

# Start chatbot

# Ask the user for input

# Respond based on keywords

# Exit when the user types bye
print("=====================================")
print(" Welcome to the Student Help Chatbot ")
print("=====================================")
print("Type 'help' for available commands.")
print("Type 'bye' to exit.\n")

while True:

    question = input("You: ").lower()

    if question == "hello":
        print("Bot: Hello! How can I help you today?")

    elif question == "help":
        print("Bot: I can answer:")
        print("- hello")
        print("- office hours")
        print("- library")
        print("- fees")
        print("- contact")
        print("- bye")

    elif question == "office hours":
        print("Bot: Monday to Friday, 8 AM to 5 PM.")

    elif question == "library":
        print("Bot: The library is open from 8 AM to 10 PM.")

    elif question == "fees":
        print("Bot: Please contact the Finance Office.")

    elif question == "contact":
        print("Bot: Email: support@university.edu")

    elif question == "bye":
        print("Bot: Goodbye! Have a great day!")
        break

    else:
        print("Bot: Sorry, I don't understand that question.")